// +build ignore

package main

import (
	"flag"
	"fmt"
	"io"
	"os"

	"layeh.com/radius/dictionary"
)

func main() {
	outputFile := flag.String("o", "-", "Output filename")
	flag.Parse()

	parser := &dictionary.Parser{
		Opener: &dictionary.FileSystemOpener{},
	}

	dict := &dictionary.Dictionary{}

	for _, filename := range flag.Args() {
		nextDict, err := parser.ParseFile(filename)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}

		if err := MergeDict(dict, nextDict); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}

	var w io.Writer
	if *outputFile == "-" {
		w = os.Stdout
	} else {
		f, err := os.OpenFile(*outputFile, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0644)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		defer f.Close()
		w = f
	}

	fmt.Fprintln(w, "// Code generated by generate_main.go. DO NOT EDIT.")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "package debug")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, `import "layeh.com/radius/dictionary"`)
	fmt.Fprintln(w, "")
	fmt.Fprintf(w, "var IncludedDictionary = %#v\n", dict)
}

func MergeDict(d1, d2 *dictionary.Dictionary) error {
	// TODO: vendor merging

	// Duplicate checks
	for _, attr := range d2.Attributes {
		existingAttr := dictionary.AttributeByName(d1.Attributes, attr.Name)
		if existingAttr == nil {
			existingAttr = dictionary.AttributeByName(d1.Attributes, attr.OID)
		}

		if existingAttr != nil {
			return fmt.Errorf("duplicate attribute %s (%s)", attr.Name, attr.OID)
		}
	}

	// Merge
	d1.Attributes = append(d1.Attributes, d2.Attributes...)
	d1.Values = append(d1.Values, d2.Values...)

	return nil
}
