// Generated by radius-dict-gen. DO NOT EDIT.

package rfc5176

import (
	"net"
	"strconv"

	"layeh.com/radius"

	. "layeh.com/radius/rfc3576"
)

var _ = radius.Type(0)
var _ = strconv.Itoa
var _ = net.ParseIP

func init() {
	ErrorCause_Strings[ErrorCause_Value_InvalidAttributeValue] = "Invalid-Attribute-Value"
	ErrorCause_Strings[ErrorCause_Value_MultipleSessionSelectionUnsupported] = "Multiple-Session-Selection-Unsupported"
}

const (
	ErrorCause_Value_InvalidAttributeValue               ErrorCause = 407
	ErrorCause_Value_MultipleSessionSelectionUnsupported ErrorCause = 508
)
