# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10

    working_directory: /go/src/layeh.com/radius
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: go install layeh.com/radius/cmd/radius-dict-gen
      - run: go install layeh.com/radius/cmd/radserver
      - run: go install layeh.com/radius/cmd/radtest
