// Code generated by radius-dict-gen. DO NOT EDIT.

package rfc4603

import (
	. "layeh.com/radius/rfc2865"
)

func init() {
	NASPortType_Strings[NASPortType_Value_PPPoA] = "PPPoA"
	NASPortType_Strings[NASPortType_Value_PPPoEoA] = "PPPoEoA"
	NASPortType_Strings[NASPortType_Value_PPPoEoE] = "PPPoEoE"
	NASPortType_Strings[NASPortType_Value_PPPoEoVLAN] = "PPPoEoVLAN"
	NASPortType_Strings[NASPortType_Value_PPPoEoQinQ] = "PPPoEoQinQ"
}

const (
	NASPortType_Value_PPPoA      NASPortType = 30
	NASPortType_Value_PPPoEoA    NASPortType = 31
	NASPortType_Value_PPPoEoE    NASPortType = 32
	NASPortType_Value_PPPoEoVLAN NASPortType = 33
	NASPortType_Value_PPPoEoQinQ NASPortType = 34
)
