// Code generated by radius-dict-gen. DO NOT EDIT.

package nokiapss1830

import (
	"strconv"

	"layeh.com/radius"
	"layeh.com/radius/rfc2865"
)

const (
	_NokiaPSS1830_VendorID = 7483
)

func _NokiaPSS1830_AddVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	var vsa radius.Attribute
	vendor := make(radius.Attribute, 2+len(attr))
	vendor[0] = typ
	vendor[1] = byte(len(vendor))
	copy(vendor[2:], attr)
	vsa, err = radius.NewVendorSpecific(_NokiaPSS1830_VendorID, vendor)
	if err != nil {
		return
	}
	p.Add(rfc2865.VendorSpecific_Type, vsa)
	return
}

func _NokiaPSS1830_GetsVendor(p *radius.Packet, typ byte) (values []radius.Attribute) {
	for _, avp := range p.Attributes {
		if avp.Type != rfc2865.VendorSpecific_Type {
			continue
		}
		attr := avp.Attribute
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _NokiaPSS1830_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				values = append(values, vsa[2:int(vsaLen)])
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _NokiaPSS1830_LookupVendor(p *radius.Packet, typ byte) (attr radius.Attribute, ok bool) {
	for _, avp := range p.Attributes {
		if avp.Type != rfc2865.VendorSpecific_Type {
			continue
		}
		attr := avp.Attribute
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _NokiaPSS1830_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				return vsa[2:int(vsaLen)], true
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _NokiaPSS1830_SetVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	for i := 0; i < len(p.Attributes); {
		avp := p.Attributes[i]
		if avp.Type != rfc2865.VendorSpecific_Type {
			i++
			continue
		}
		vendorID, vsa, err := radius.VendorSpecific(avp.Attribute)
		if err != nil || vendorID != _NokiaPSS1830_VendorID {
			i++
			continue
		}
		for j := 0; len(vsa[j:]) >= 3; {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa[j:]) || vsaLen < 3 {
				i++
				break
			}
			if vsaTyp == typ {
				vsa = append(vsa[:j], vsa[j+int(vsaLen):]...)
			}
			j += int(vsaLen)
		}
		if len(vsa) > 0 {
			copy(avp.Attribute[4:], vsa)
			i++
		} else {
			p.Attributes = append(p.Attributes[:i], p.Attributes[i+i:]...)
		}
	}
	return _NokiaPSS1830_AddVendor(p, typ, attr)
}

func _NokiaPSS1830_DelVendor(p *radius.Packet, typ byte) {
vsaLoop:
	for i := 0; i < len(p.Attributes); {
		avp := p.Attributes[i]
		if avp.Type != rfc2865.VendorSpecific_Type {
			i++
			continue
		}
		vendorID, vsa, err := radius.VendorSpecific(avp.Attribute)
		if err != nil || vendorID != _NokiaPSS1830_VendorID {
			i++
			continue
		}
		offset := 0
		for len(vsa[offset:]) >= 3 {
			vsaTyp, vsaLen := vsa[offset], vsa[offset+1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				continue vsaLoop
			}
			if vsaTyp == typ {
				copy(vsa[offset:], vsa[offset+int(vsaLen):])
				vsa = vsa[:len(vsa)-int(vsaLen)]
			} else {
				offset += int(vsaLen)
			}
		}
		if offset == 0 {
			p.Attributes = append(p.Attributes[:i], p.Attributes[i+1:]...)
		} else {
			i++
		}
	}
	return
}

type NokiaRole uint32

const (
	NokiaRole_Value_NokiaObserver      NokiaRole = 0
	NokiaRole_Value_NokiaProvisioner   NokiaRole = 1
	NokiaRole_Value_NokiaAdministrator NokiaRole = 2
	NokiaRole_Value_NokiaCrypto        NokiaRole = 4
)

var NokiaRole_Strings = map[NokiaRole]string{
	NokiaRole_Value_NokiaObserver:      "Nokia-Observer",
	NokiaRole_Value_NokiaProvisioner:   "Nokia-Provisioner",
	NokiaRole_Value_NokiaAdministrator: "Nokia-Administrator",
	NokiaRole_Value_NokiaCrypto:        "Nokia-Crypto",
}

func (a NokiaRole) String() string {
	if str, ok := NokiaRole_Strings[a]; ok {
		return str
	}
	return "NokiaRole(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func NokiaRole_Add(p *radius.Packet, value NokiaRole) (err error) {
	a := radius.NewInteger(uint32(value))
	return _NokiaPSS1830_AddVendor(p, 1, a)
}

func NokiaRole_Get(p *radius.Packet) (value NokiaRole) {
	value, _ = NokiaRole_Lookup(p)
	return
}

func NokiaRole_Gets(p *radius.Packet) (values []NokiaRole, err error) {
	var i uint32
	for _, attr := range _NokiaPSS1830_GetsVendor(p, 1) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, NokiaRole(i))
	}
	return
}

func NokiaRole_Lookup(p *radius.Packet) (value NokiaRole, err error) {
	a, ok := _NokiaPSS1830_LookupVendor(p, 1)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = NokiaRole(i)
	return
}

func NokiaRole_Set(p *radius.Packet, value NokiaRole) (err error) {
	a := radius.NewInteger(uint32(value))
	return _NokiaPSS1830_SetVendor(p, 1, a)
}

func NokiaRole_Del(p *radius.Packet) {
	_NokiaPSS1830_DelVendor(p, 1)
}
